name: 'Enforce PR labels for Github Actions'
description: 'Enforce PR labels for Github Actions'
author: 'Yogev Ben David'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  REQUIRED_LABELS_ANY:
    description: 'Require at least one label'
    required: true
    default: ""
  REQUIRED_LABELS_ALL:
    description: 'Require all labels'
    required: true
    default: ""
  BANNED_LABELS:
    description: 'Banned'
    required: true
    default: ""