name: Enforce PR labels for Github Actions

on: [pull_request]

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/require-label-action@master
      with:
        valid-labels: "bug,enhancement,feature"
