name: Enforce PR labels for Github Actions

on:
  pull_request:
    types: [opened, labeled, unlabeled]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@master
      with:
        # REQUIRED_LABELS_ANY: "bug,enhancement,feature"
        BANNED_LABELS: "banned"
